### ISSUE TITLE
Quick Questions

### ISSUE THREAD

**Issue by gjsman** [cyrildewit/eloquent-viewable#113]
- Eloquent Viewable: 2.4.1
- Laravel Version: 5.7
- PHP Version: 7.0
- Database Driver & Version: MariaDB

Hi,

I am writing my app, and it has some unique requirements which I am struggling to make Eloquent Viewable work for.

1. I have custom IDs for each "page", and must use these custom IDs in my database instead of the primary, auto-incrementing key. I have tried extending/overriding the `addView` function, but need help.

2. My "pages" are grouped into "categories", and I need to be able to see the amount of views per category as well as per page. What is the best way to do this / is this even possible?

Gabriel

**Comment by cyrildewit** [comment]
Hi @gjsman,

**Regarding question one**
What do you exactly mean? Are you using a different name for the primary key column? For example: `identifier`instead of `id`. I think that I covered this by using `$model->getKey()`. See https://laravel.com/docs/5.7/eloquent#defining-models. Scroll down until you see heading titled: 'Primary Keys
'

**Regarding question two**

You mean tagging? This is (at the moment) not possible. I still have to find a suitable solution. I have planned this feature for version 3.0. See issue #84.

**Comment by gjsman** [comment]
Question 1 appears to solve it for me, thanks!
Question 2... tagging would be helpful. I have found less efficient ways to do what I need though, so, until then, I think I am good. I will reopen if I need anything else.
