### ISSUE TITLE
orderByUniqueViews() doesn't work like expected.

### ISSUE THREAD

**Issue by mauriziocalarese** [cyrildewit/eloquent-viewable#144]
- Eloquent Viewable: 3.1
- Laravel Version: 5.7.21
- PHP Version: 7.1.7

### Description:
When  I try to get a collection of the most viewed items, using orderByUniqueViews(), I get back a views array with **ALL** the views from the same visitor, so not unique views and it's ordered by **TOTAL** number of views.

### Steps To Reproduce:

This to track the view:
``` 
       views($item)
            ->overrideVisitor(request()->ip())
            ->record();
```

This to get the most viewed ordered by unique views
```
public function mostViewed()
    {
        return $this->itemRepository
            ->orderByUniqueViews()
            ->get();
    }
```

#### Expected behavior:
I expect, using orderByUniqueViews(), to get a collection ordered by **unique** views, with an array "views"that contains only **unique views**.

Event better could be to have only the total number of unique views, all the data related to the views could not be necessary. At least in my case.
Is there maybe something already implemented for this?

#### Actual behavior:
I get a collection ordered by all the views, the array 'views' contains all the views.

Thank you in advance for your time, help and availability ;)

**Comment by mauriziocalarese** [comment]
Hi @cyrildewit,
any feedback on this? :(

**Comment by cyrildewit** [comment]
@mauriziocalarese in `v2` I used a leftjoin to count the related unique views, but in `v3` I switched to `withCount`. I took a look at the query yesterday and I found out that the output of the SQL query wasn't as expected. I tried to write my own SQL query based on what it's currently outputting, but I wasn't able to solve it.

This is the current SQL query (formatted):

```sql
select `cyrildewit_eloquent-viewable-57`.`posts`.*,
(
    select count(*)
    from `cyrildewit_eloquent-viewable-57`.`views`
    where `posts`.`id` = `views`.`viewable_id`
    and `views`.`viewable_type` = 'App\Post'
) as `views_count`

from `cyrildewit_eloquent-viewable-57`.`posts`
order by `views_count` desc
```

I modified it to:

```sql
select `cyrildewit_eloquent-viewable-57`.`posts`.*,
(
    select count(distinct visitor)
    from `cyrildewit_eloquent-viewable-57`.`views`
    where `posts`.`id` = `views`.`viewable_id`
    and `views`.`viewable_type` = 'App\Post'
) as `views_count`

from `cyrildewit_eloquent-viewable-57`.`posts`
order by `views_count` desc
```

I now solved the problem that `distinct visitor` was missing, but the next problem lays in the where statement: ``views`.`viewable_type` = 'App\Post'`. If I replace all the classnames with for example `someRandomString` (without a backslah), it works.

I still have to figure something out that will solve it, but it might take a while because I'm quite busy with school.

---

![ordered posts](https://user-images.githubusercontent.com/16477999/52072559-7ed0c500-2585-11e9-8408-67a7cf1b4783.PNG)

![views](https://user-images.githubusercontent.com/16477999/52072547-79737a80-2585-11e9-9914-6712f007c7ae.PNG)

**Comment by mauriziocalarese** [comment]
Thank you for the kind and detailed feedback :)
No pressure, was only to know something more about it 👍 

Have a nice weekend.

**Comment by mauriziocalarese** [comment]
Hi Cyril,
do you have any news about this bug?

**Comment by cyrildewit** [comment]
@mauriziocalarese I am very busy right now. I have a test week over 3 weeks and I also need to work. I assure you that I will try to solve it afterwards. This time, I need to find a solution that is suiteable for most projects. I will probably revert it back to `v2`. I will see.

**Comment by mauriziocalarese** [comment]
Thanks for the answer :)
Waiting for it, in this case ;)

**Comment by cyrildewit** [comment]
@mauriziocalarese a fix is on its way 🎉. I need to decide if I'm going to release it as a patch or major version 🤔. It's tough. It's, in theory, a breaking change because the behavior and the underlying query is different. I also didn't change the API, so people won't really notice it unless they are testing the behavior.
