### ISSUE TITLE
delayInSession() not working with queues

### ISSUE THREAD

**Issue by MarcoCazzaro** [cyrildewit/eloquent-viewable#164]
- Eloquent Viewable: 3.2.0
- Laravel Version: 5.8.21
- PHP Version: 7.3.6
- Database Driver & Version:

### Description:
When using delayInSession() in a queued job, the views are counted every time. Perhaps because the session gets regenerated every time you run the job?

### Steps To Reproduce:

1. Create a job like this:

        <?php

        namespace App\Jobs;

        use Illuminate\Bus\Queueable;
        use Illuminate\Queue\SerializesModels;
        use Illuminate\Queue\InteractsWithQueue;
        use Illuminate\Contracts\Queue\ShouldQueue;
        use Illuminate\Foundation\Bus\Dispatchable;

        class ProcessView implements ShouldQueue
        {
            use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

            protected $viewable;
            protected $user_id;

            /**
             * Create a new job instance.
             *
             * @return void
             */
            public function __construct($viewable, $user_id)
            {
                $this->viewable = $viewable;
                $this->user_id = $user_id;
            }

            /**
             * Execute the job.
             *
             * @return void
             */
            public function handle()
            {
                if (is_null($this->user_id)) {
                    views($this->viewable)
                        ->delayInSession(now()->addMinutes(30))
                        ->record();
                } else  {
                    views($this->viewable)
                        ->overrideVisitor($this->user_id)
                        ->delayInSession(now()->addMinutes(30))
                        ->record();
                }
            }
        }

2. Dispatch the job

#### Expected behavior:

If I run the job several times in the same 30 minutes window passing the same user ID, I expect one view count only.

#### Actual behavior:

If I run the job several times in the same 30 minutes window passing the same user ID, I get several views count.

**Comment by cyrildewit** [comment]
Because Cron Jobs run in a new session. See https://stackoverflow.com/questions/37417559/trying-to-access-session-data-from-a-queued-job-in-laravel-5-2 Thus when the job is being run, it doesn't have access to the view history.

To fix this you first need to check if we should record the view, based on the history. If true, dispatch the job without the `delayInSession()`. This can be achieved by using the ViewSessionHistory class. To see an example, look in the Views class for the shouldRecord method.

Maybe I can think of an alternative solution for this. Like extracting that logic and making it public.

**Comment by kfirba** [comment]
@cyrildewit I think that making the `shouldRecord()` method public would be great.
