### ISSUE TITLE
Uniquie views via API doesn't count

### ISSUE THREAD

**Issue by ErriourRU** [cyrildewit/eloquent-viewable#193]
- Eloquent Viewable: 4.1.1
- Laravel Version: 6.14.0
- PHP Version: 7.3.13
- Database Driver & Version: Mysql (MariaDB 10.4.11)

### Description:
If I'm trying to writing views in API request, I've got all views as unique. (I use it in Vue)

### Steps To Reproduce:

1. Get post collection
2. `views($post)->record();`
3. In return `views($post)->unique()->count()`

#### Expected behavior:
View records including user API token or IP.

#### Actual behavior:
All views record as uniquie, if API used.

**Comment by cyrildewit** [comment]
This package uses a cookie to distinguish a unique visitor, but the api middleware group doesn't contain the `Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse` middleware.

That's why it's possible to supply your own unique visitor id from the client-side. See https://github.com/cyrildewit/eloquent-viewable#supplying-your-own-visitors-id-and-ip-address
