### ISSUE TITLE
Error when using on a morph to many

### ISSUE THREAD

**Issue by Teranode** [cyrildewit/eloquent-viewable#209]
- Eloquent Viewable: 4.0-5.0
- Laravel Version: 6.0
- PHP Version: 7.3.x
- Database Driver & Version: MaraiaDB 10.3

### Description:
Im currently utilizing octobercms and it has this model relation called attachmany, which is basically a morph to many for attaching multiple files or images. The issue that occurs is that if i use eloquent viewable with this model relations i get this error: 

```
Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to CyrildeWit\EloquentViewable\CooldownManager::push() must implement interface CyrildeWit\EloquentViewable\Contracts\Viewable, null given, called in /var/www/data/www/vendor/cyrildewit/eloquent-viewable/src/Views.php on line 316 in /var/www/data/www/vendor/cyrildewit/eloquent-viewable/src/CooldownManager.php:48
```

This has been happening since v4, it happens every time a view tries to get recorded.

**Comment by cyrildewit** [comment]
Can you post your code? I think I know why.

**Comment by Teranode** [comment]
```
    public function newView(Request $request)
    {
        $video = Encode::where('embed_code', $request->input('id'))->first();

        $expiresAt = now()->addHours(1);
        views($video)->cooldown($expiresAt)->record();

        return response()->json(['data' => 'Successfully Viewed']);
    }
```

**Comment by cyrildewit** [comment]
Thanks for posting.

The argument error probably occurs because you're trying to use the `->cooldown()` method on a `Views` instance with a null as viewable. This may happen when for example the $video variable is null or when you leave the $viewable argument empty: `views()->...`.

In your case you should throw a 404 error when your $video is null or use the `findOrFail` method:

```php
$video = Encode::where('embed_code', $request->input('id'))->firstOrFail();
```

Can you confirm this by logging the value of the $video variable?
