### ISSUE TITLE
Forbid Export Data

### ISSUE THREAD

**Issue by robertnicjoo** [cyrildewit/eloquent-viewable#53]
- Laravel Page View Counter Version: 0.1.7
- Laravel Version: 5.5.39
- PHP Version: 7.1.12
- Database Driver & Version: MySQL 5.7.19

### Description:

Your application works like charm, thank you!

The issue i'm facing is when I export my data as `CSV` it is included page views info (if i'm not mistake 5 columns will add to my CSV file)

**Question:**

How can I ban (forbid) your package of having access to my database export?

**Comment by cyrildewit** [comment]
@robertnicjoo I see that you are using `v0.1`. This version appends attributes to your Eloquent model. The problem with this is that developers can't remove them from the attribute list. I changed this in `v1.0`. Instead of appending attributes to your model, you can use some methods.

You can find more information about mutators & accessors in the  [documentation](https://laravel.com/docs/5.6/eloquent-mutators#accessors-and-mutators).

I suggest you to upgrade the package to `v1.0`. There are some breaking changes, so you have to replace some lines of code.

Instead of getting the views via `$postModel->page_visits`, you will have to use `$postModel->getPageViewsFrom(Carbon::now()->subDays(1))`.  There are more methods available now. See [README](https://github.com/cyrildewit/laravel-page-view-counter/tree/1.0) of `1.0` branch.

You also have to add the collumn `ip_address` to your views table.

```
$table->string('ip_address')->nullable();
```

Creating a new feature branch might be useful before upgrading!

Please let me know if you need any further information.

**Comment by cyrildewit** [comment]
@robertnicjoo I've updated the above post to help you a little bit more!

**Comment by robertnicjoo** [comment]
@cyrildewit  I appreciate your help 🥇 , I will edit all my files and let you know if there is any other issue.
