### ISSUE TITLE
getUniquePageViews() multiple create

### ISSUE THREAD

**Issue by cihanx** [cyrildewit/eloquent-viewable#61]
- Laravel Page View Counter Version: 1.0
- Laravel Version: 5.6
- PHP Version: 7.1.3
- Database Driver & Version: MySQL 10.1.30-MariaDB

I used getUniquePageViews() but doing multiple recordings my SQL on localhost

image -> http://prntscr.com/j6h4in
image -> http://prntscr.com/j6h52v

**Comment by cihanx** [comment]
Is it problematic to have multiple records of the same type?
Does the database get tired?

**Comment by Teranode** [comment]
that was the initial issue i was having with that @cihanx . It would eventually lead to an overbloated table filled with the same data. I previously suggested that if the person ends up having the same session id or ip address for that viewable type it would just increment a row column by 1 rather than creating an entirely new row for it that way you can read from that.
