### ISSUE TITLE
After database migration from v1.0 to v2.0 . The getView functionality doesn't add views on the post. 

### ISSUE THREAD

**Issue by SqrFactor** [cyrildewit/eloquent-viewable#76]
$post->addView(); is adding the views for the post in database but there are two problems: 
1. The visitor column is not adding IP but some key. Please check the screenshot.
2. The getView() functionality is not fetching the new added views from the table. 

![image](https://user-images.githubusercontent.com/16622319/41640677-24e56c0a-7480-11e8-9e2d-fdeac3eca313.png)

**Comment by cyrildewit** [comment]
I've replaced the `ip address` with something more secure. It will now contain a unique key that's stored inside a cookie.

- https://www.quora.com/Which-is-the-best-way-to-count-unique-visitors-for-every-web-page-of-my-website-I-am-considering-two-methods-using-cookies-and-using-IP-addresses-server-log-file

I think the reason why the views count is not incrementing, is because the `cache.enabled` option is set to true. Check the config file. To do a quick test, run `php artisan cache:clear` and reload the page.
