### ISSUE TITLE
First it recordas the ip, then the cookie (2 diff visits)

### ISSUE THREAD

**Issue by wipit** [cyrildewit/eloquent-viewable#79]
- Laravel Version: 5.6
- PHP Version: 7.1

First it recordas the ip, then the cookie (like 2 diff visits)
and the getviews() always returns 2 (?)

i don't know if i'm doing something wrong

**Comment by cyrildewit** [comment]
Hey @wipit,

Sorry for the delayed response. I was on vacation last week.

> First it recordas the ip, then the cookie (like 2 diff visits)

What do you mean exactly? After upgrading from v1 to v2? Or does it store two views at a time?

> and the getviews() always returns 2 (?)

This is probably because caching is turned on as default. Check the config file to turn it off, if you want. I still need to document this in the readme to avoid confusion!
