### ISSUE TITLE
Views count not working

### ISSUE THREAD

**Issue by armagedan** [cyrildewit/eloquent-viewable#91]
- Eloquent Viewable: 2.3.0
- Laravel Version: 5.6

Here is the problem. I was previously using v2.2.0 and the same thing occurred. Did not notice this before until I did a clean refresh of my DB for testing before I updated to 2.3.0.

Detail:
I used both `getUniqueViews()` and `getViews()` and the same result shows. The problem is that this won't count the number of views unless I do a `php artisan cache:clear` every time. Once I clear the cache and refresh the page, `getUniqueViews()` or `getViews()` works perfectly fine. Any idea why this is being caused? Like I mentioned, This was happening on v2.0 too.

**Comment by cyrildewit** [comment]
This is probably because caching is turned on. See `eloquent-viewable.cache.enabled` and `eloquent-viewable.cache.cache_views_count.enabled` at the config file.

**Comment by armagedan** [comment]
Sorry did not notice that. What are the cons of disabling cache? And what are the pros of keeping it enabled?

**Comment by armagedan** [comment]
Ok then I will keep it disabled. I can still queue the viewable instead of using cache right? What would be the difference there?

**Comment by cyrildewit** [comment]
> What would be the difference there?

Instead of blocking the request with connecting with the database and storing the view, it will add it to a queue. Your request will move on and the user hopefully doesn't have to wait. I never used the queue in real life, but I added this feature in case someone wanted it.

It's only useful if you have a special database available like Redis, Amazon SQS, Beanstalkd etc. Using it with database as driver, doesn't provide any faster speed, but will slow it down.

**Comment by armagedan** [comment]
Yes but it is an alternative to caching if I were to disable cache. Correct?

**Comment by cyrildewit** [comment]
No, the queue is for **saving the views** and the cache is for **counting the views**.

**Comment by armagedan** [comment]
Ok the confusion is now cleared :)
